#!/usr/bin/env ruby

# Pour lancer le script il faut ruby, rubygems et la gem nokogiri

require 'rubygems'
require 'nokogiri'
require 'erb'

data = File.read('Amdts_spectre_1.txt')
sections = data.scan(%r(<Amend>.+?</Amend>)m)

  
template = ERB.new File.read('template.erb'), nil, '-'

File.open "result.mediawiki", "w" do |f|
  sections.each do |xml|
    doc = Nokogiri::XML(xml)

    num, note = doc.css('NumAm').text.split(' ', 2)
    note.gsub!(/\s/, '') if note
    
    color = case note.to_s.gsub(/[^-+]/, '')
      when "--"
        "red"
      when "-"
        "IndianRed"
      when "++"
        "green"
      when "+"
        "lightgreen"
      when ""
        "lightgrey"
      else
        raise "Invalid note: #{note.inspect}"
    end
    
    infos = xml.scan(%r(Text proposed by the Commission\nAmendment\n(.+)\nOr.)m).first
    raise "No info found" unless infos
    
    
    infos = infos.first.split(/\n/)

    commission_rows = []
    amendement_rows = []
    infos.each_slice(2) do |commission, amendement|
      commission_rows << commission
      amendement_rows << amendement
    end
    
    [commission_rows, amendement_rows].each do |rows|
      rows.delete_if { |row| row.nil? or row.empty? }
    end
    
    members = doc.css('Members').text
    article = doc.css('Article').text

    f.puts template.result(binding)
  end
end
